<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Log-booklet v1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Log_intro_frTeX_files/libs/clipboard/clipboard.min.js"></script>
<script src="Log_intro_frTeX_files/libs/quarto-html/quarto.js"></script>
<script src="Log_intro_frTeX_files/libs/quarto-html/popper.min.js"></script>
<script src="Log_intro_frTeX_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Log_intro_frTeX_files/libs/quarto-html/anchor.min.js"></script>
<link href="Log_intro_frTeX_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Log_intro_frTeX_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Log_intro_frTeX_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Log_intro_frTeX_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Log_intro_frTeX_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Log-booklet v1</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="an-introduction-to-logarithms" class="level1">
<h1>An introduction to Logarithms</h1>
<section id="j.m.-alonso" class="level4">
<h4 class="anchored" data-anchor-id="j.m.-alonso">J.M. Alonso</h4>
<p>The first time I heard the word <strong>logarithm</strong> was in High School. A strange word with no discernible meaning, an obscure concept that nobody could defined because, as I was to learn later, we lacked the mathematical background.</p>
<p>Like everybody else, I was simply confronted with a book, about a 100 pages long, filled with tightly packed ciphers, a totally incomprehensible blob: the (in?)famous <em>Table of Logarithms</em> (see <a href="#fig-logtbl" class="quarto-xref">Figure&nbsp;4</a>). This only added to the mystery and awe that I felt around the notion. Eventually, I learnt how to use this table, mainly to compute <strong>compound interest</strong>, a classical problem in economics.</p>
<div id="nte-compound" class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note&nbsp;1: Compound interest
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose you deposit a certain amount, <span class="math inline">\(C\)</span>, in a Bank. After an agreed amount of time has passed, the Bank pays you <strong>interest</strong>, which you deposit again, adding to the capital for which the Bank will pay you interest in the <em>next</em> period. Compound interest is the problem of computing the capital you will received from the Bank, after you have repeated this process <span class="math inline">\(n\)</span> times. This amount equals <span class="math inline">\(C\cdot (1+r)^n\)</span>, where <span class="math inline">\(r\)</span> is the interest rate agreed with the Bank. If the interest rate is, say, <span class="math inline">\(6.5\%\)</span>, then <span class="math inline">\(1+r=1.065\)</span>. See also <a href="#nte-e" class="quarto-xref">Note&nbsp;4</a>.</p>
</div>
</div>
<p>This was in the 60’s, a time when a table of logarithms was the best tool you had for such computations. In those days, I was very curious about logarithms, and would have loved to have answers to questions like these ones:</p>
<ul>
<li>Whodunit?</li>
<li>When?</li>
<li>Where?</li>
<li>Why?</li>
<li>How?</li>
<li>What are logarithms?</li>
<li>How many are there?</li>
<li>Logs in statistics</li>
<li>Logs everywhere</li>
</ul>
</section>
<section id="whodunit-when-where" class="level2">
<h2 class="anchored" data-anchor-id="whodunit-when-where">Whodunit? When? Where?</h2>
<p>The culprit was Sir <strong>John Napier</strong> (1550-1617), a Scottish mathematician (see <a href="#fig-Napier" class="quarto-xref">Figure&nbsp;1</a>). He was born and lived his life at Merchiston Tower in Edinburgh (the tower is now a part of Merchiston campus, Edinburgh Napier University). He was actually the <em>laird</em> of Merchiston, a Scottish title that he translates to Latin as <em>Barone Merchistonii</em>, baron of Merchiston (cf. <a href="#fig-covers" class="quarto-xref">Figure&nbsp;2</a>).</p>
<p>Inventing logarithms and computing them was the culmination of 20+ years of hard work. In 1614 he published <em>Mirifici logarithmorum canonis descriptio</em> (Description of the wonderful canon of logarithms), see <a href="#fig-covers" class="quarto-xref">Figure&nbsp;2</a> Descriptio.</p>
<div id="fig-Napier" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Napier-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="John_Napier.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>John Napier</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Merchiston_Tower.png" class="img-fluid figure-img" style="width:78.0%"></p>
<figcaption>Merchiston Tower</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-Napier-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1
</figcaption>
</figure>
</div>
<p>He presented his calculations in table form, the once famous and much used logarithm tables. You can see a page from Henry Briggs’ 1617 <em>Logarithmorum Chilias Prima</em> showing the common logarithm (<a href="#fig-logtbl" class="quarto-xref">Figure&nbsp;4</a>) of the integers 0 to 67 to thirteen exact decimal places.</p>
<div id="fig-covers" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-covers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Descriptio.png" class="img-fluid figure-img" style="width:94.0%"></p>
<figcaption>Descriptio</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Constructio.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Constructio</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-covers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Covers
</figcaption>
</figure>
</div>
<p>In 1619 Napier’s son Robert published <em>Mirifici logarithmorum canonis constructio</em> (<a href="#fig-covers" class="quarto-xref">Figure&nbsp;2</a> Constructio) explaining his calculation methods.</p>
<p>Napier invented the word <strong>logarithm = logos + arithmos</strong>, roughly <strong>proportions and numbers</strong>. He was also responsible for introducing the dot to indicate decimals, as in <span class="math inline">\(\pi\sim 3.14159\)</span>.</p>
<p><em>Descriptio</em> was an instant success. Well, <em>instant</em> for the European XVII century, that is!</p>
<ul>
<li>By 1615 the book was translated into English, spreading quickly in England and continental Europe.</li>
<li>In 1620 Kepler dedicated his book <em>Epheresis</em> to Napier. Unaware of Napier’s death in 1619, in the book Kepler congratulated Napier on his invention and its benefits to astronomy.</li>
<li>In 1914, the English mathematician E.W. Hobson called logarithms “one of the very greatest scientific discoveries that the world has seen”.</li>
</ul>
</section>
<section id="why" class="level2">
<h2 class="anchored" data-anchor-id="why">Why?</h2>
<p>To understand this success and Hobson’s remark one should realize that computations where made by hand, a laborious and error prone process. Only in the 1970’s, with the advent of the hand-held electronic calculator, where these methods discarded, particularly with the introduction of personal computers.</p>
<p>So let’s take a step back and consider how would you go about computing multiplication, division, extraction of roots, or powers of numbers. All this had to be done by hand, with only paper and pen.</p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise: multiplication by hand
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you remember the algorithm to multiply two numbers, I invite you to compute <span class="math inline">\(x\cdot y\)</span> for any pair of integers <span class="math inline">\(x,y\)</span> of your choice, having at least 10 non-zero digits each.</p>
</div>
</div>
<p>After you try this excercise I think you will agree wholeheartedly with these words of John Napier:</p>
<blockquote class="blockquote">
…nothing is more tedious, fellow mathematicians, in the practice of the mathematical arts, than the great delays suffered in the tedium of lengthy multiplications and divisions, the finding of ratios, and in the extraction of square and cube roots? [with] the many slippery errors that can arise? I have found an amazing way of shortening the proceedings…
</blockquote>
<p>In short, a great aid to calculations before the invention of computers!</p>
<p>Another important use of logarithms is making large numbers more manageable, easier to understand. Even in the age of computers, we continue to use logarithmic scales to better understand large numbers, as in the graph describing the German hyperinflation in the early 1920’s (<a href="#fig-germanINFL" class="quarto-xref">Figure&nbsp;3</a>).</p>
<div id="fig-germanINFL" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-germanINFL-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="GermanINFL.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-germanINFL-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: The german hyperinflation of the 1920’s
</figcaption>
</figure>
</div>
</section>
<section id="how" class="level2">
<h2 class="anchored" data-anchor-id="how">How?</h2>
<p>The idea is to transform your data (the numbers <span class="math inline">\(x,y\)</span> whose product we wish to compute) in such a way that multiplication is transformed into adddition, a much easier and shorter operation. How?</p>
<div id="fig-logtbl" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-logtbl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Briggs1617.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-logtbl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Page of Briggs table of logarithms (1617)
</figcaption>
</figure>
</div>
<p>Let’s pause to look at Briggs table of <span class="math inline">\(\log_{10}\)</span> <a href="#fig-logtbl" class="quarto-xref">Figure&nbsp;4</a> in some detail. Let’s give a name to the parts of real numbers; for instance the number 617,953.7459281 has an <strong>integral part</strong> and decimals which, in the context of tables of logarithms, is called <strong>mantissa</strong> (the word comes from Latin and means “something added”): <span class="math display">\[
\underbrace{617,953}_\text{integral part}.
\underbrace{7459281}_\text{mantissa}
\]</span></p>
<p>Back to Briggs table. The first column contains the <strong>natural</strong> numbers, i.e.&nbsp;<span class="math inline">\(1, 2, 3, 4, 5, \dots,n, \dots\)</span>. The <span class="math inline">\(\log_{10}(n)\)</span> is contained in the next two columns: the second column contains the integral part, and the third the mantissa.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The logarithm table is a <strong>dictionary</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>A good way to think of the table is as a dictionary, say LT, where LT.keys() is the first column, and the LT.values() are given in the next two columns.</li>
</ul>
</div>
</div>
<p>There are three values in the page shown that you should pay attention to: the values of <span class="math inline">\(\log_{10}(n)\)</span> for <span class="math inline">\(n=1,10,100\)</span> (100 is at the bottom right of <a href="#fig-logtbl" class="quarto-xref">Figure&nbsp;4</a>, on the barely visible page 2 of the table). You can check that these values are, respectively, 0, 1, and 2. Note that the mantissae in Briggs table contain 14 places.</p>
<p>Let’s build our own (mini) logarithm table (<a href="#tbl-mini" class="quarto-xref">Table&nbsp;1</a>). The table contains two columns.The second column is the <strong>arithmetic</strong> sequence <span class="math inline">\(0, 1,2,\dots,11,12\)</span> (a sequence is called arithmetic when the difference between a number and its predecesor is constant; in our case, equal to 1), and the first column is <strong>geometric</strong> (the quotient of a number to its predecesor is constant, in our case, equal to 2). It is easy to see how the table is built: reading it from right to left, we see that to each natural number <span class="math inline">\(0, 1, 2, \dots,n,\)</span> etc., there corresponds, respectively, <span class="math inline">\(1=2^0, 2=2^1, 4=2^2, \dots, 4096 = 2^{12}\)</span>.</p>
<div id="tbl-mini" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-mini-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1
</figcaption>
<div aria-describedby="tbl-mini-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<style>
    .center-table{
        margin-left: auto;
        margin-right: auto;
    }
</style>

<table class="center-table">
<style>
tr:nth-child(even) {
  background-color: #f2f2f2;
}
table {
  border-collapse: collapse;
  border-spacing: 50px 0;
}

th,td {
  padding: 5px ;
}
</style>


    <thead>
      <tr><th colspan="2"> Mini table of logarithms </th>
    </tr></thead>


  <tbody><tr> 
    <td>1</td>
    <td>0</td>
  </tr>
  <tr class="darker">
    <td>2</td>
    <td>1</td>
  </tr>
  <tr>
    <td>4</td>
    <td>2</td>
  </tr>
  <tr class="darker">
    <td>8</td>
    <td>3</td>
  </tr>
  <tr>
    <td>16</td>
    <td>4</td>
  </tr>
  <tr class="darker">
    <td>32 *</td>
    <td>5 </td>
  </tr>
  <tr>
    <td>64</td>
    <td>6</td>
  </tr>
  <tr class="darker">
    <td>128 *</td>
    <td>7 </td>
  </tr>
  <tr>
    <td>256</td>
    <td>8</td>
  </tr>
  <tr class="darker">
    <td>512</td>
    <td>9</td>
  </tr><tr>
    <td>1024</td>
    <td>10</td>
  </tr>
  <tr class="darker">
    <td>2048</td>
    <td>11</td>
  </tr>
  <tr>
    <td>4096</td>
    <td>12</td>
  </tr>
</tbody></table>
</div>
</figure>
</div>
<p>From left to right, we can read the logarithm, in a way similar to that of Briggs table. In this case, the logarithm we have computed (for only a few, very special, numbers, but still) is <span class="math inline">\(\log_2\)</span>, the logarithm to base 2 (more about this in the next section). Let’s denote this map simply <span class="math inline">\(L\)</span>; so for instance, <span class="math inline">\(L(8)=3\)</span>, <span class="math inline">\(L(512)=9\)</span>, and so on. The map we obtain when reading from right to left will be denoted <span class="math inline">\(E\)</span>, for exponential; for example, <span class="math inline">\(E(10)=1024\)</span>, and <span class="math inline">\(E(0)=1\)</span>. <span class="math inline">\(E\)</span> and <span class="math inline">\(L\)</span> are said to be <em>inverse</em> to each other, in the sense that <span class="math inline">\(L\)</span> “undoes” what <span class="math inline">\(E\)</span> does, and viceversa.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Encyclopedia Britannica definition of logarithm (XVIII century)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>You should now be able to make some sense of EB’s rather cryptic “definition”:
<ul>
<li>the indices of the ratios of numbers to one another; being a series of numbers in arithmetical progression, corresponding to others in geometrical progression; by means of which, arithmetical calculations can be made with much more ease and expedition than otherwise.</li>
</ul></li>
</ul>
</div>
</div>
<p>How did Napier used his table? Like this: suppose we want to multiply, say, <span class="math inline">\(32\cdot 128\)</span>, the numbers marked with asterisks in <a href="#tbl-mini" class="quarto-xref">Table&nbsp;1</a>. We proceed as follows: we compute <span class="math inline">\(L(32),L(128)\)</span> and add these numbers: <span class="math display">\[
L(32)+L(128)= 5+7=12
\]</span> Now we read the table from right to left (i.e.&nbsp;apply <span class="math inline">\(E\)</span>) at the entry 12, and get the result = 4096. The calculation we have done can be expressed in this formula: <span class="math display">\[
L(32\cdot 128) = L(32)+L(128).
\]</span> In words, <span class="math inline">\(L\)</span> transforms a <em>product</em> into an <em>addition</em>.</p>
<blockquote class="blockquote">
<p>This property actually <em>defines</em> the logarithms (see the next Section)</p>
</blockquote>
<div id="nte-def" class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note&nbsp;2: <strong>Conclusions from our mini table of logarithms</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Reading the table from right to left we have the <strong>function</strong> <span class="math inline">\(E\)</span>, for <em>exponential</em>: <span class="math inline">\(E(n)=2^n\)</span></li>
<li>Reading the table from left to right, we have the logarithm: <span class="math inline">\(L(n)=\log_2(n)\)</span>.</li>
<li><span class="math inline">\(E\)</span> and <span class="math inline">\(L\)</span> are <strong>inverse</strong> to each other. Thus,
<ul>
<li><span class="math inline">\(\log_2(x)=y\)</span> means <span class="math inline">\(x = 2^y\)</span></li>
</ul></li>
<li>This can be taken as a <strong>definition</strong> of logarithm to base 2.</li>
<li>In general:
<ul>
<li><span class="math inline">\(\log_b(x) = y\)</span> means <span class="math inline">\(x=b^y\)</span>.</li>
</ul></li>
</ul>
</div>
</div>
<p>We saw in <a href="#nte-def" class="quarto-xref">Note&nbsp;2</a> that exponentiation can be used to define the logarithms. Using this definition requires, however, that we know what the exponential functions are, and that we know how to compute them. It is easy enough (even if tedious!) to compute <span class="math display">\[
2^n=\overbrace{2\cdot 2 \cdots 2}^\text{$n$ times}
\]</span> for many integers <span class="math inline">\(n\)</span>. But what about <span class="math inline">\(2^x\)</span> for real numbers <span class="math inline">\(x\)</span>, as in <span class="math inline">\(2^{1.5}\)</span>, or maybe <span class="math inline">\(2^{\sqrt{2}}\)</span>. Exponential functions of the form <span class="math inline">\(b^x\)</span> for <span class="math inline">\(b&gt;0\)</span> and any real <span class="math inline">\(x\)</span>, can be defined and computed exactly by means of <strong>infinite power series</strong>.</p>
<div id="nte-series" class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note&nbsp;3: <strong>In detail</strong>: Definition by infinite power series
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p><span class="math inline">\(e^x = 1+ \sum_{n=1}^{\infty} (1/n!) x^n = 1+x+x^2/2 + x^3/6+ \cdots \,\)</span>,</p></li>
<li><p>For <span class="math inline">\(x\in (-1,1)\)</span>,</p></li>
</ul>
<p><span class="math display">\[\ln(1+x) = \sum_{n=1}^{\infty} (-1)^{n+1} x^n/n \, =\, x-x^2/2+x^3/3- \cdots  \]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>By the way!</strong>: Note that
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[
2^n=\overbrace{2\cdot 2 \cdots 2}^\text{$n$ times}, \text{ implies } \log(2^n)= \overbrace{\log(2)+\log(2)+\cdots+\log(2)}^\text{$n$ times} = n\cdot \log(2)
\]</span></p>
<p>and, more generally:</p>
<ul>
<li><span class="math inline">\(\log(x^y)=y\cdot \log(x)\)</span></li>
</ul>
</div>
</div>
<p>Infinite series like those in <a href="#nte-series" class="quarto-xref">Note&nbsp;3</a>, are computed by taking <strong>partial sums</strong>: <span class="math display">\[
S_i(x):= \sum_{n=1}^i (- 1)^{n+1} x^i/i = x-x^2/2 + \cdots \]</span> and examining wether or not the <span class="math inline">\(S_i(x)\)</span> (for fixed <span class="math inline">\(x\)</span> and <span class="math inline">\(i=1,2,\dots\)</span>) <strong>converge</strong>. In other words, the series is defined to be <span class="math inline">\(\lim_{i\rightarrow \infty} S_i(x)\)</span>. The partial sums are polynomials that <strong>approximate</strong> the value of the series.</p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise: approximate log
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Use partial sums <span class="math inline">\(S(i)\)</span> to approximate <span class="math inline">\(\ln (1.5)\)</span>. Check how good these approximations are, for several values of <span class="math inline">\(i\)</span>.</p></li>
<li><p>Do the same for the exponential <span class="math inline">\(e^x\)</span>, to approximate the number <span class="math inline">\(e \sim 2.71828\)</span>. How many summands you need to obtain this approximation to <span class="math inline">\(e\)</span>?</p></li>
<li><p>If you want to compute <span class="math inline">\(\ln (1.5)\)</span> with 3 exact decimals, how large must <span class="math inline">\(i\)</span> be?</p></li>
</ul>
</div>
</div>
</section>
<section id="what-are-logarithms-how-many-are-there" class="level2">
<h2 class="anchored" data-anchor-id="what-are-logarithms-how-many-are-there">What are logarithms? How many are there?</h2>
<p>The short answer is: the logarithms are a family of functions, denoted <span class="math inline">\(\log\)</span>, having in common the following <strong>fundamental property</strong>: <span class="math display">\[
\log(x\cdot y)=\log(x)+\log(y),
\]</span> where <span class="math inline">\(x,y\)</span> are positive real numbers.</p>
<p>And yes, there are many logarithms, but they have the same fundamental property expressed by the above formula: they transform products into sums. To distinguish among different elements of the family, we decorate the logarithm thus: <span class="math inline">\(\log_b\)</span>, read as “logarithm to the base <span class="math inline">\(b\)</span>”, where <span class="math inline">\(b\)</span> is any real number such that <span class="math inline">\(b&gt;1\)</span>.</p>
<div id="cell-fig-logs" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| lst-label: lst-plot</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math <span class="im">as</span> ma</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">#define constant function</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> const1(x):</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">0</span><span class="op">*</span>x<span class="op">+</span><span class="dv">1</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create x and y ranges</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(<span class="fl">0.1</span>, <span class="dv">15</span>, <span class="dv">1000</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>y1 <span class="op">=</span> np.log2(x)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>y2 <span class="op">=</span> np.log(x)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>y3 <span class="op">=</span> np.log10(x)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>y4 <span class="op">=</span> const1(x)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot both functions</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>ax.plot(x, y1, label<span class="op">=</span><span class="st">'log2'</span>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>ax.plot(x, y2, label<span class="op">=</span><span class="st">'log'</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>ax.plot(x, y3, label<span class="op">=</span><span class="st">'log10'</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>ax.plot(x, y4, <span class="st">'k'</span>,label<span class="op">=</span><span class="st">'const1'</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co">#ax.set_title('A few logarithms', size=14)</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="dv">0</span>, <span class="dv">15</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="op">-</span><span class="dv">2</span>, <span class="dv">4</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-logs" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-logs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Log_intro_frTeX_files/figure-html/fig-logs-output-1.png" width="569" height="416" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-logs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: A few logarithms
</figcaption>
</figure>
</div>
</div>
</div>
<p>The code produces <a href="#fig-logs" class="quarto-xref">Figure&nbsp;5</a> that shows <span class="math inline">\(\log_2, \log_e=\ln\)</span>, and <span class="math inline">\(\log_{10}\)</span>. By the way, the figure shows the usual way to depict functions (real functions, that is!).</p>
<p>Note that the domain of the logarithms is the set of positive real number, and their values are the set of real numbers. We see clearly that the logarithms are <strong>increasing</strong> functions, i.e.&nbsp;<span class="math inline">\(x&lt;y\)</span> implies <span class="math inline">\(\log(x) &lt; \log(y)\)</span>, and that all their values at one equal 0.</p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise: the integral part of the log
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Suppose that <span class="math inline">\(4 &lt; \log_{10} x &lt; 5\)</span>. What can you say about <span class="math inline">\(x\)</span>? How large is it? Can it be, for instance, <span class="math inline">\(&gt; 100,000\)</span>?</p></li>
<li><p>What can you say about <span class="math inline">\(x\)</span> if you know that <span class="math inline">\(10 &lt; \log_{2} x &lt; 11\)</span> ?</p></li>
<li><p>Motivate your answers!</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>In detail: functions and inverse functions</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>A function <span class="math inline">\(y=f(x)\)</span> is like a python dictionary d</strong></p>
<ul>
<li><p>The set of <strong>keys</strong> is called the <strong>domain</strong> of <span class="math inline">\(F\)</span>, denoted <span class="math inline">\(D(f)\)</span>. In mathematical notation, <span class="math inline">\(x\)</span> represents any of the keys of d, and it is called the <em>independent variable</em></p></li>
<li><p>The set of <strong>values</strong> of d is called the <strong>range</strong> of <span class="math inline">\(f\)</span>, denoted <span class="math inline">\(R(f)\)</span>. The <em>dependent variable</em> <span class="math inline">\(y\)</span> represents the value of <span class="math inline">\(f\)</span> at <span class="math inline">\(x\)</span>, i.e.&nbsp;d[x]</p></li>
</ul>
<p><strong>Conclusion</strong>: the logarithm is a function. Tables of logarithms are representations of logarithms as dictionaries.</p>
<ul>
<li><p>Dictionaries can sometimes be composed: if the values of dictionary d1 are accepted by d2 as keys, then you can define a new dictionary, d1[d2] (se code below).</p></li>
<li><p>Some dictionaries can be reversed, i.e.&nbsp;you can swap keys with values and viceversa. In the context of functions, the reverse dictionary is denoted <span class="math inline">\(f^{-1}\)</span> and is called the <em>inverse function of <span class="math inline">\(f\)</span></em>.</p></li>
<li><p>Thinking of dictionaries, it is clear that <span class="math inline">\(f^{-1}(f(x))=x\)</span>, and <span class="math inline">\(f(f^{-1}(y))=y\)</span>. In words, <span class="math inline">\(f^{-1}\)</span> “undoes” what <span class="math inline">\(f\)</span> does, and viceversa.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>In detail</strong>: the fundamental property defines the logarithms
</div>
</div>
<div class="callout-body-container callout-body">
<p>For any number <span class="math inline">\(b&gt;1\)</span>, there exists one and only one continuous function <span class="math inline">\(f\)</span> with <span class="math inline">\(D(f)=(0,\infty)\)</span> and <span class="math inline">\(R(f)=(-\infty, \infty)\)</span>, such that <span class="math inline">\(f(xy)=f(x)+f(y)\)</span> and <span class="math inline">\(f(b)=1\)</span>.</p>
</div>
</div>
<p>Consider the following dictionaries and their inverses:</p>
<div id="fb8f4ee7" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#define two dictionaries</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>d1<span class="op">=</span>{<span class="op">-</span><span class="dv">1</span>:<span class="op">-</span><span class="dv">2</span>, <span class="dv">0</span>:<span class="dv">0</span>,<span class="dv">1</span>:<span class="dv">2</span>,<span class="dv">2</span>:<span class="dv">4</span>}</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>d2<span class="op">=</span>{ <span class="op">-</span><span class="dv">1</span>:<span class="dv">1</span>, <span class="dv">0</span>:<span class="dv">0</span>, <span class="dv">1</span>:<span class="dv">1</span>,<span class="dv">2</span>:<span class="dv">4</span>,<span class="op">-</span><span class="dv">2</span>:<span class="dv">4</span>}</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">#invert the dictionaries</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>inv_d1 <span class="op">=</span> {v: k <span class="cf">for</span> k, v <span class="kw">in</span> d1.items()}</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>inv_d2 <span class="op">=</span> {v: k <span class="cf">for</span> k, v <span class="kw">in</span> d2.items()}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>You can think of d1 as being part of the function <span class="math inline">\(f(x)=2 x\)</span>. Similarly, d2 is a portion of <span class="math inline">\(g(x)=x^2\)</span>. Inspect inv_d1 and inv_d2. Can you see any difference? Explain!</p>
<div id="d6c0d6af" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#compute the compositions</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>inv_d1_d1 <span class="op">=</span> {v:inv_d1[d1[v]] <span class="cf">for</span> v <span class="kw">in</span> d1.keys()}</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>d1_inv_d1 <span class="op">=</span> {k:d1[inv_d1[k]] <span class="cf">for</span> k <span class="kw">in</span> inv_d1.keys()}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise: dictionaries and inverses
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>In the last bit of code, for both dictionaries, we have computed the two compositions. Note that for <span class="math inline">\(\textrm{d1}=f\)</span>, we have <span class="math inline">\(f^{-1}(f(x))=x\)</span>, and <span class="math inline">\(f(f^{-1}(y))=y\)</span>, as explained above. But, what happens when we do the same for d2? Why? What is going on? Explain!</li>
</ul>
</div>
</div>
<p>As mentioned earlier, Napier invented and computed <span class="math inline">\(\ln\)</span>, the <strong>natural</strong> or <strong>neperian</strong> logarithm, <span class="math inline">\(\ln = \log_e\)</span>, where <span class="math inline">\(e\sim 2.71828\)</span> is a well-known and famous constant (it can be computed in several ways, for instance, as the infinite series <span class="math inline">\(e=\sum_{n=0}^\infty 1/n!\)</span>. Why?). Henry Briggs introduced and computed the more familiar <span class="math inline">\(\log_{10}\)</span>, the common logarithm. Note the value of <span class="math inline">\(x\)</span> at which each graph intersects the horizontal line at hight <span class="math inline">\(=1\)</span>: it is the base of the corresponding logarithm.</p>
<div id="nte-e" class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note&nbsp;4: The number <span class="math inline">\(e\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Jacob Bernoulli discovered <span class="math inline">\(e\)</span> in 1683 while studying a question about <strong>compound interest</strong> (cf. <a href="#nte-compound" class="quarto-xref">Note&nbsp;1</a>). Suppose you start with <span class="math inline">\(C=1\)</span> and the Bank pays 100% interest per year. When the interest is credited only once, at the end of the year, the value is 2. But if you compute and add the interest twice in the year, then the compund interest is <span class="math inline">\(1 \cdot 1.5^2 =2.25\)</span>. If instead, you compound four times in a year, the account yields <span class="math inline">\(1 \cdot 1.25^4 \sim 2.4414\)</span>; if you compound every month it yields <span class="math inline">\(1\cdot (1+100/12)^{12} \sim 2.613035\)</span>. Bernouilli proved that this sequence has a limit for more and smaller compounding intervals. In other words, that <span class="math display">\[
\lim_{n\rightarrow \infty} \Big(1+\frac{1}{n}\Big)^n
\]</span> exists and equals <span class="math inline">\(e\)</span>. So, when the interest is compounded continually, the yield equals <span class="math inline">\(e\)</span>.</p>
<ul>
<li><p>It is intersting to note that some 70 years earlier, Napier had defined the natural logarithm, without knowing <span class="math inline">\(e\)</span>!</p></li>
<li><p>There are many reasons why <span class="math inline">\(e\)</span> is a <strong>very</strong> special number. For one, the family of exponential functions <span class="math inline">\(y=b^x + \text{constant}\)</span>, has derivative <span class="math inline">\(y'=y\cdot \ln(b)\)</span>. It follows that <span class="math inline">\(y'=y\)</span> if and only if <span class="math inline">\(b=e\)</span>. So, the only functions <span class="math inline">\(y=f(x)\)</span> whose derivative coincides with the function, <span class="math inline">\(y'=y\)</span>, is <span class="math inline">\(y=e^x + \text{constant}\)</span>. For another, the power series defining <span class="math inline">\(b^x\)</span>: <span class="math display">\[
b^x = 1+\sum_{n=1}^\infty \frac{x \ln b}{1!} + \frac{(x \ln b)^2}{2!} + \cdots + \frac{(x \ln b)^n}{n!} + \cdots
\]</span> has a neat form only for <span class="math inline">\(b=e\)</span> (cf. <a href="#nte-series" class="quarto-xref">Note&nbsp;3</a>).</p></li>
<li><p>It was the Swiss mathematician Leonhard Euler (1707-1783) who first used the letter <span class="math inline">\(e\)</span> to represent this constant, around 1727.</p></li>
<li><p>Finally, let’s mention the famous <strong>Euler’s identity</strong> relating the five most famous numbers of mathematics: <span class="math display">\[
e^{i \pi} +1 = 0
\]</span></p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise: approximate log
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Convince yourself that the limit in <a href="#nte-e" class="quarto-xref">Note&nbsp;4</a> exists</p></li>
<li><p>If you want to compute <span class="math inline">\(e\sim 2.71828\)</span> with these many exact decimals, how large must <span class="math inline">\(n\)</span> be?</p></li>
<li><p>As mentioned earlier, you can also compute <span class="math inline">\(e\)</span> as the series <span class="math inline">\(\sum 1/n!\)</span>. Which method converges faster (and, hence, is preferable when computing <span class="math inline">\(e\)</span>?).</p></li>
</ul>
</div>
</div>
<section id="more-approximations-of-the-logarithm" class="level3">
<h3 class="anchored" data-anchor-id="more-approximations-of-the-logarithm">More approximations of the logarithm</h3>
<p><a href="#fig-logapprox" class="quarto-xref">Figure&nbsp;6</a> shows the first four partial sums of the series for <span class="math inline">\(\ln(1+x)\)</span> (see <a href="#nte-series" class="quarto-xref">Note&nbsp;3</a>). The figure shows that the approximation is excelent around <span class="math inline">\(x=0\)</span>, i.e.&nbsp;<span class="math inline">\(ln\)</span> around 1. In the whole interval <span class="math inline">\((-1,1)\)</span> the approximation is not so good, specially near the extremes of the interval. However, it is clear that, as <span class="math inline">\(i\)</span> increases, the partial sums <span class="math inline">\(S_i(x)\)</span> yield better approximations for all <span class="math inline">\(x\in(-1,1)\)</span>.</p>
<div id="cell-fig-logapprox" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="lst-logapprox"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="lst-logapprox-1"><a href="#lst-logapprox-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="lst-logapprox-2"><a href="#lst-logapprox-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math <span class="im">as</span> ma</span>
<span id="lst-logapprox-3"><a href="#lst-logapprox-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="lst-logapprox-4"><a href="#lst-logapprox-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-logapprox-5"><a href="#lst-logapprox-5" aria-hidden="true" tabindex="-1"></a><span class="co">#define constant function</span></span>
<span id="lst-logapprox-6"><a href="#lst-logapprox-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> const1(x):</span>
<span id="lst-logapprox-7"><a href="#lst-logapprox-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">0</span><span class="op">*</span>x<span class="op">+</span><span class="dv">1</span></span>
<span id="lst-logapprox-8"><a href="#lst-logapprox-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-logapprox-9"><a href="#lst-logapprox-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create x and y ranges</span></span>
<span id="lst-logapprox-10"><a href="#lst-logapprox-10" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(<span class="op">-</span><span class="fl">0.99</span>, <span class="fl">0.99</span>, <span class="dv">1000</span>)</span>
<span id="lst-logapprox-11"><a href="#lst-logapprox-11" aria-hidden="true" tabindex="-1"></a>y0 <span class="op">=</span> np.log(<span class="dv">1</span><span class="op">+</span>x)</span>
<span id="lst-logapprox-12"><a href="#lst-logapprox-12" aria-hidden="true" tabindex="-1"></a>y1 <span class="op">=</span> x</span>
<span id="lst-logapprox-13"><a href="#lst-logapprox-13" aria-hidden="true" tabindex="-1"></a>y2<span class="op">=</span> x<span class="op">-</span>x<span class="op">**</span><span class="dv">2</span><span class="op">/</span><span class="dv">2</span></span>
<span id="lst-logapprox-14"><a href="#lst-logapprox-14" aria-hidden="true" tabindex="-1"></a>y3<span class="op">=</span> x<span class="op">-</span>x<span class="op">**</span><span class="dv">2</span><span class="op">/</span><span class="dv">2</span> <span class="op">+</span> x<span class="op">**</span><span class="dv">3</span><span class="op">/</span><span class="dv">3</span></span>
<span id="lst-logapprox-15"><a href="#lst-logapprox-15" aria-hidden="true" tabindex="-1"></a>y4 <span class="op">=</span> x<span class="op">-</span>x<span class="op">**</span><span class="dv">2</span><span class="op">/</span><span class="dv">2</span> <span class="op">+</span> x<span class="op">**</span><span class="dv">3</span><span class="op">/</span><span class="dv">3</span> <span class="op">-</span> x<span class="op">**</span><span class="dv">4</span><span class="op">/</span><span class="dv">4</span></span>
<span id="lst-logapprox-16"><a href="#lst-logapprox-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-logapprox-17"><a href="#lst-logapprox-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="lst-logapprox-18"><a href="#lst-logapprox-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot both functions</span></span>
<span id="lst-logapprox-19"><a href="#lst-logapprox-19" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="lst-logapprox-20"><a href="#lst-logapprox-20" aria-hidden="true" tabindex="-1"></a><span class="co">#ax.plot(x, y0, 'k', label='log10 (1+x)')</span></span>
<span id="lst-logapprox-21"><a href="#lst-logapprox-21" aria-hidden="true" tabindex="-1"></a>ax.plot(x, y1, label<span class="op">=</span><span class="st">'S1(x) = x'</span>)</span>
<span id="lst-logapprox-22"><a href="#lst-logapprox-22" aria-hidden="true" tabindex="-1"></a>ax.plot(x, y2, label<span class="op">=</span><span class="st">'S2(x) = x - x^2/2'</span>)</span>
<span id="lst-logapprox-23"><a href="#lst-logapprox-23" aria-hidden="true" tabindex="-1"></a>ax.plot(x, y3, label<span class="op">=</span><span class="st">'S3(x) = x - x^2/2 + x^3/3'</span>)</span>
<span id="lst-logapprox-24"><a href="#lst-logapprox-24" aria-hidden="true" tabindex="-1"></a>ax.plot(x, y4, label<span class="op">=</span><span class="st">'S4(x) = x - x^2/2 + x^3/3 - x^4/4'</span>)</span>
<span id="lst-logapprox-25"><a href="#lst-logapprox-25" aria-hidden="true" tabindex="-1"></a>ax.plot(x, y0, <span class="st">'k'</span>, label<span class="op">=</span><span class="st">'log10 (1+x)'</span>)</span>
<span id="lst-logapprox-26"><a href="#lst-logapprox-26" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="op">-</span><span class="fl">0.9</span>, <span class="dv">1</span>)</span>
<span id="lst-logapprox-27"><a href="#lst-logapprox-27" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="op">-</span><span class="fl">1.5</span>, <span class="dv">1</span>)</span>
<span id="lst-logapprox-28"><a href="#lst-logapprox-28" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="lst-logapprox-29"><a href="#lst-logapprox-29" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="lst-logapprox-30"><a href="#lst-logapprox-30" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-logapprox" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-logapprox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Log_intro_frTeX_files/figure-html/fig-logapprox-output-1.png" width="597" height="416" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-logapprox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Approximation of ln(1+x) by partial sums
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise: approximate <span class="math inline">\(ln(1+x)\)</span> for <span class="math inline">\(x&gt;1\)</span>.
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Use the partial sum <span class="math inline">\(S_3(x)\)</span> to approximate <span class="math inline">\(\ln(10)\)</span>, so that the first 6 decimals of the approximation coincide with <span class="math inline">\(\ln(10)\)</span>.</p></li>
<li><p>Do the same to approximate <span class="math inline">\(\ln(100)\)</span>.</p></li>
</ul>
</div>
</div>
</section>
</section>
<section id="the-logarithm-in-statistics" class="level2">
<h2 class="anchored" data-anchor-id="the-logarithm-in-statistics">The logarithm in statistics</h2>
<p>In statistics, working with the logarithms of data rather than the data themselves may have several advantages. Multiplicative relationships may become additive, skewed distributions may become symmetrical, and curves may become straight lines.</p>
<div id="fig-nhanes" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nhanes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Histogr.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Histogram</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="HistogrLOG.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Histogram of log of the data</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-nhanes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7
</figcaption>
</figure>
</div>
<p>The log transformation is often used to reduce skewness of a measurement variable. If, after transformation, the distribution is symmetric, or close to normal, then one can use a number of tools to improve comparisons among different groups, or to determine reference intervals. The left-hand side of <a href="#fig-nhanes" class="quarto-xref">Figure&nbsp;7</a> shows that the distribution of urine albumin is skewed to the right with a long right tail. The right-hand side of <a href="#fig-nhanes" class="quarto-xref">Figure&nbsp;7</a> shows the histogram for <span class="math inline">\(\log_{10}(\textrm{albumin})\)</span>, and includes a fitted curve representing the normal distribution, with the same mean and standard deviation. This is data of The National Health and Nutrition Examination Study (NHANES) (UK), from 2017 – 2018. The sample consisted of 494 males and 524 females.</p>
</section>
<section id="logs-everywhere-the-logarithmic-spiral" class="level2">
<h2 class="anchored" data-anchor-id="logs-everywhere-the-logarithmic-spiral">Logs everywhere: the logarithmic spiral</h2>
<ul>
<li>Albrecth Dürer (1525) called the logarithmic spiral <em>eternal line</em></li>
<li>Descartes studied it in 1638</li>
<li>Jacob Bernoulli (1655-1705) called it <em>Spira mirabilis</em>, the marvelous spiral. Bernoulli was fascinated by the fact that, although the spiral grows larger at every turn, the form remains the same (a phenomenon called <em>self-similarity</em>). Bernoulli wanted to have a spiral engraved on his headstone along with the phrase <em>Eadem mutata resurgo</em> (“Although changed, I shall arise the same”)</li>
</ul>
<p>In <strong>polar coordinates</strong> <span class="math inline">\((r,\theta)\)</span>, the equations for the spiral are:</p>
<p><span class="math display">\[
r = a e^{k\theta}, \, \theta \in \mathbb{R};\,\, \theta =(1/k) \ln r/a, \,\, \textrm{where }a&gt;0,\, b\neq 0 \textrm{ are real constants.}
\]</span></p>
<div id="fig-everyw" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-everyw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="LogSpiral.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Logarithmic spiral</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MandelbrotSet.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Mandelbrot Set</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-everyw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8
</figcaption>
</figure>
</div>
<p>Figure <a href="#fig-everyw" class="quarto-xref">Figure&nbsp;8</a> (left) shows how the spiral looks. And <a href="#fig-everyw" class="quarto-xref">Figure&nbsp;8</a> (right) shows a small portion of Mandelbrot’s set: talk about spirals everywhere! I will be very glad if this picture makes you curious about the Mandelbrot set.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Spectacular videos of the Mandelbrot set
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://www.quantamagazine.org/the-quest-to-decode-the-mandelbrot-set-maths-famed-fractal-20240126/?mc_cid=7b8025d489&amp;mc_eid=a118cbcf70" class="uri">https://www.quantamagazine.org/the-quest-to-decode-the-mandelbrot-set-maths-famed-fractal-20240126/?mc_cid=7b8025d489&amp;mc_eid=a118cbcf70</a></p>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>